chore: don't exit on error with iptables TCPMSS
Add error handling to iptables TCPMSS command.

In Ubuntu 24.04 with linux kernel 6.8. this command returns an error, likely due to the removal of iptables in favor of nftables.

Without this iptables rule, the program still works fine.

Error: iptables: No chain/target/match by that name.